# Generated by Django 2.0 on 2018-04-15 16:39

import csustm.file_validation
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', csustm.file_validation.ContentTypeRestrictedFileField(blank=True, default='none.jpg', null=True, upload_to=csustm.file_validation.get_upload_image)),
                ('quotes', models.CharField(blank=True, max_length=155)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
                ('degree', models.CharField(max_length=155)),
                ('teacher_account', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', related_query_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ClassName')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
        ),
    ]
