# Generated by Django 2.0 on 2018-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('code', models.CharField(max_length=155, unique=True, verbose_name='code')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, choices=[('Passaporte', 'Passaporte'), ('Carta de Conducao', 'Carta de Conducao'), ('BI', 'BI'), ('DIRE', 'DIRE')], max_length=255)),
                ('doc_id', models.CharField(blank=True, max_length=155)),
                ('contact1', models.IntegerField(blank=True, null=True)),
                ('contact2', models.IntegerField(blank=True, null=True)),
                ('enrollment_year', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
